# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- serviceAccount.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
