apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-microservice
  labels:
    app: devops-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-microservice
  template:
    metadata:
      labels:
        app: devops-microservice
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: devops-workload-identity
      containers:
      - name: devops-microservice
        image: devops-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: workload-identity-secret
              key: client-id
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: workload-identity-secret
              key: tenant-id
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/azure/tokens/azure-identity-token
        - name: AZURE_KEY_VAULT_URL
          valueFrom:
            secretKeyRef:
              name: workload-identity-secret
              key: key-vault-url
