apiVersion: v1
kind: Service
metadata:
  name: devops-microservice
  labels:
    app: devops-microservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: devops-microservice
