apiVersion: v1
kind: Secret
metadata:
  name: workload-identity-secret
  namespace: default
type: Opaque
stringData:
  client-id: ""  # Will be populated by Terraform
  tenant-id: ""  # Will be populated by Terraform
  key-vault-url: ""  # Will be populated by Terraform