# k8s/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: prod

images:
- name: placeholder.acr.io/app
  newName: acrproddevopsapp.azurecr.io/devops-app # El ACR de PROD
  newTag: "v1.0.0" # El pipeline puede parchear esto

patches:
- target:
    kind: ServiceAccount
    name: devops-app-sa
  patch: |-
    - op: replace
      path: /metadata/annotations/azure.workload.identity~1client-id
      value: "CLIENT_ID_DE_PROD" # El pipeline reemplaza esto
- target:
    kind: Deployment
    name: devops-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "https://kv-prod-devops-app.vault.azure.net" # URL del KV de PROD
