name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd app
        pytest test/

    - name: Build Docker image
      run: |
        cd app
        docker build -t devops-microservice .
